namespace Core.Enums
{
    public enum SortingParam
    {
        NameDesc,
        Name,
        EndDateDesc,
        EndDate,
        StartDate,
        StartDateDesc,
        LastDate,
        LastDateDesc,
        Date,
        DateDesc,
        Created,
        CreatedDesc,
        AttemptCount,
        AttemptCountDesc,
        AttemptDuration,
        AttemptDurationDesc,
        Points,
        PointsDesc,
        RightAnswers,
        RightAnswersDesc,
        AvgTime,
        AvgTimeDesc,
        AvgPoints,
        AvgPointsDesc,
        FirstName,
        FirstNameDesc
    }
}
